module.exports = {
    MESSAGE_RECEIVED: 'SUPPORT_LIVE_CHAT_MESSAGE_RECEIVED',
    MESSAGE_DELETED: 'SUPPORT_LIVE_CHAT_MESSAGE_DELETED',
    USER_TYPEING: 'SUPPORT_LIVE_CHAT_USER_TYPING',
    USER_STOPPED_TYPING : 'SUPPORT_LIVE_CHAT_USER_STOPPED_TYPING',
    I_AM_TYPING: 'SUPPORT_LIVE_CHAT_I_AM_TYPING',
    I_STOPPED_TYPING: 'SUPPORT_LIVE_CHAT_I_STOPPED_TYPING',
    CONVERSATION_DELETED: 'SUPPORT_LIVE_CHAT_CONVERSATION_DELETED',
	MESSAGE_DELETED: 'SUPPORT_LIVE_CHAT_MESSAGE_DELETED',
	MESSAGE_READ: 'MESSAGE_READ'
};